/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#fcf8fa',
        'secondary-fixed': '#d3e4fe',
        primary: '#000000',
        'tertiary-container': '#271901',
        'surface-container': '#f0edef',
        'on-error': '#ffffff',
        'surface-tint': '#565e74',
        'inverse-surface': '#303032',
        'tertiary-fixed-dim': '#dec29a',
        'surface-variant': '#e4e2e4',
        'on-tertiary': '#ffffff',
        'on-primary-fixed-variant': '#3f465c',
        'surface-container-highest': '#e4e2e4',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#54647a',
        error: '#ba1a1a',
        'on-tertiary-fixed': '#271901',
        'tertiary-fixed': '#fcdeb5',
        'outline-variant': '#c6c6cd',
        'surface-dim': '#dcd9db',
        'surface-container-high': '#eae7e9',
        tertiary: '#000000',
        'primary-fixed-dim': '#bec6e0',
        'on-secondary-fixed': '#0b1c30',
        'inverse-on-surface': '#f3f0f2',
        'primary-fixed': '#dae2fd',
        'surface-bright': '#fcf8fa',
        'on-primary-container': '#7c839b',
        'on-tertiary-container': '#98805d',
        'error-container': '#ffdad6',
        'on-background': '#1b1b1d',
        'secondary-container': '#d0e1fb',
        'on-surface-variant': '#45464d',
        'on-surface': '#1b1b1d',
        secondary: '#505f76',
        'on-secondary-fixed-variant': '#38485d',
        outline: '#76777d',
        'on-primary': '#ffffff',
        background: '#fcf8fa',
        'on-primary-fixed': '#131b2e',
        'on-error-container': '#93000a',
        'inverse-primary': '#bec6e0',
        'surface-container-low': '#f6f3f5',
        'surface-container-lowest': '#ffffff',
        'secondary-fixed-dim': '#b7c8e1',
        'primary-container': '#131b2e',
        'on-tertiary-fixed-variant': '#574425',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        base: '4px',
        xs: '4px',
        xl: '40px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        gutter: '24px',
        'margin-mobile': '16px',
        'margin-desktop': '32px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'code-md': ['13px', { lineHeight: '18px', fontWeight: '500' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'title-lg': ['18px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
}
